### PR TITLE
Refactoring for Python3

### PR DESCRIPTION
**Pull request by k2-gc**
Refactored the code seems for python2 and modified for python3.
Mainly, 
* xrange -> range
* import error
* And some other errors when using with python3

I checked and tested my programs by "testUserDemos.py" on env below.
* Python 3.10.12
* Ubuntu 22.04

### CODE REVIEW

**Comment by nightrome** [comment]
Can you verify that your changes are also backward-compatible with Python 2.7 ?

**Comment by k2-gc** [comment]
@nightrome 
OK, I will check it as soon as possible!
Please wait a minutes.

BTW, this is just my interest but  is it needed that our code can run with Python 2.7?

**Comment by nightrome** [comment]
The project has been starred 181 times and a number of other repos probably import it. So it is crucial that it remains backward-compatible, to avoid breaking them.

**Comment by k2-gc** [comment]
OK, Thanks.
I am gonna confirm whether the code can execute with Python2.7.

**Comment by k2-gc** [comment]
Sorry, my codes didn't work with python2.7.
I will fix and modify them.

**Comment by k2-gc** [comment]
Sorry, my codes didn't work with python2.7.
But I already found the way to use the code with both py2 and py3.
I will fix and modify them and re-PR soon.
Thakns.

**Pull request closed without merging**
